### ISSUE TITLE
Is it a bug within xztl_media_check()?

### ISSUE THREAD

**Issue by shampoo365** [OpenMPDK/xZTL#1]
`static int xztl_media_check (struct xztl_media *media)
{
    struct xztl_mgeo *g;

    /* Check function pointers */
    if (!media->init_fn)
	return XZTL_NOINIT;

    if (!media->init_fn).  --------------------------------> Does it should be 'if(!media->exit_fn)'?
	return XZTL_NOEXIT;

    if (!media->submit_io)
	return XZTL_MEDIA_NOIO;

    if (!media->zone_fn)`

**Comment by qihui81** [comment]
yes, correct, I'll submit a PR to fix it

**Comment by qihui81** [comment]
it's fixed in v0.3 release
