### ISSUE TITLE
is libxnvme_3p.h still used in xZTL?

### ISSUE THREAD

**Issue by cheolho-kang** [OpenMPDK/xZTL#7]
Hello, I'm cheolho kang in DSK,
when I compile the xZTL to use rocksdb-zns. I got the error log.

```
$ make lib-only
```

```
/home/chkang0912/pbssd/lib/xZTL/src/ztl-media.c:20:10: fatal error: libxnvme_3p.h: No such file or directory
   20 | #include <libxnvme_3p.h>
```

Looking at the xnvme commit logs, it looks like header file name changed "libxnvme_3p" changed to "libxnvme_libconf".
Should I change the header file of the xZTL codes myself?

For reference, the xnvme version I am using is 0.1.0.

[xnvme commit log](https://github.sec.samsung.net/DS8-MemoryOpenSource/xnvme/commit/06bf8dda8a5d08d8d7ba5e077f5417816ae61ca5)

**Comment by qihui81** [comment]
No, it's obsolete. 
Sorry, the master branch was not updated. Now it syncs with the 0.4 release.
